### ISSUE TITLE
setup_script.sh 파이썬 버젼

### ISSUE THREAD

**Issue by chowhi123** [devinlife/torrent_web_scraper#4]
전 무슨 이유에서든지 3.7이 안깔려서 https://linuxize.com/post/how-to-install-python-3-7-on-ubuntu-18-04/
요기 나온 방법대로 매뉴얼로 3.7설치했습니다. 그 뒤에 나무지는 작동이 잘되네요!

**Comment by devinlife** [comment]
파이썬 설치는 되어 있다는 가정에서 torrent_web_scraper 스크립트 사용 방법을 설명한 것이네요. 이 점에 대해 설명이 부족했나봅니다. 파이썬 설치는 다른 곳의 가이드를 따라서 3.7 버전을 설치하는 것이 맞겠네요.
